/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.blackbudha.gui;

import javax.swing.JFileChooser;
import org.blackbuddha.logic.FileTypes;
import org.blackbuddha.logic.Service;

/**
 *
 * @author prmaod
 */
public class SecongPane extends javax.swing.JPanel {

    /**
     * Creates new form SecongPane
     */
    String emailOutString;
    String phoneOutString;
    public SecongPane() {
        initComponents();
        emailPath.setEnabled(false);
        phonePath.setEnabled(false);
        saveEmail.setEnabled(false);
        savePhone.setEnabled(false);
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        uploadEmailFile = new javax.swing.JButton();
        emailPath = new javax.swing.JTextField();
        saveEmail = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnPhoneList = new javax.swing.JButton();
        phonePath = new javax.swing.JTextField();
        savePhone = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Valid Email Extraction")))));

        uploadEmailFile.setText("Upload Email File");
        uploadEmailFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadEmailFileActionPerformed(evt);
            }
        });

        saveEmail.setText("Save");
        saveEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saveEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(uploadEmailFile)
                        .addComponent(emailPath, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(uploadEmailFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveEmail)
                .addGap(0, 43, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Valid Phone Extraction\n"));

        btnPhoneList.setText("Upload Phone File");
        btnPhoneList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhoneListActionPerformed(evt);
            }
        });

        phonePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonePathActionPerformed(evt);
            }
        });

        savePhone.setText("Save");
        savePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePhoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(savePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnPhoneList)
                        .addComponent(phonePath, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnPhoneList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phonePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(savePhone)
                .addGap(0, 49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void uploadEmailFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadEmailFileActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.showDialog(file, "Choose Email Data file");
        if(file.getSelectedFile()!=null){
            String src = file.getSelectedFile().getAbsolutePath();
            emailPath.setText(src);
            emailOutString = Service.processFile(src, FileTypes.email);
            saveEmail.setEnabled(true);
        }
    }//GEN-LAST:event_uploadEmailFileActionPerformed

    private void saveEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveEmailActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.showSaveDialog(this);
        String outPath = file.getSelectedFile().getAbsolutePath();
        Service.saveData(emailOutString, outPath);
        saveEmail.setEnabled(false);
    }//GEN-LAST:event_saveEmailActionPerformed

    private void btnPhoneListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhoneListActionPerformed
        JFileChooser file = new JFileChooser();
        file.showDialog(file, "Choose Phone Data file");
        if(file.getSelectedFile()!=null){
            String src = file.getSelectedFile().getAbsolutePath();
            phonePath.setText(src);

            phoneOutString = Service.processFile(src, FileTypes.phone);
            savePhone.setEnabled(true);
        }

    }//GEN-LAST:event_btnPhoneListActionPerformed

    private void phonePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonePathActionPerformed

    private void savePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePhoneActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.showSaveDialog(this);
        String outPath = file.getSelectedFile().getAbsolutePath();
        Service.saveData(phoneOutString, outPath);
        savePhone.setEnabled(false);
    }//GEN-LAST:event_savePhoneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPhoneList;
    private javax.swing.JTextField emailPath;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField phonePath;
    private javax.swing.JButton saveEmail;
    private javax.swing.JButton savePhone;
    private javax.swing.JButton uploadEmailFile;
    // End of variables declaration//GEN-END:variables
}
